### ISSUE TITLE
Tests fail with German default locale

### ISSUE THREAD

**Issue by rmelick** [salesforce/Argus#336]
```
testHoltWintersDeviation(com.salesforce.dva.argus.service.metric.transform.HoltWintersTransformTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError
	at com.salesforce.dva.argus.service.metric.transform.HoltWintersTransformTest.testHoltWintersDeviation(HoltWintersTransformTest.java:115)

testHoltWintersForecast(com.salesforce.dva.argus.service.metric.transform.HoltWintersTransformTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError
	at com.salesforce.dva.argus.service.metric.transform.HoltWintersTransformTest.testHoltWintersForecast(HoltWintersTransformTest.java:80)
```

Improving the assert statement, the error is more useful:
```
java.lang.AssertionError: 
Expected :{2=0, 3=0.1, 4=0.27997, 5=0.72374, 6=1.57824, 7=1.56059, 8=1.46463, 9=1.45847, 10=1.47683}
Actual   :{2=0, 3=0,1, 4=0,27997, 5=0,72374, 6=1,57824, 7=1,56059, 8=1,46463, 9=1,45847, 10=1,47683}
```

**Comment by bsura** [comment]
Merged.
