### ISSUE TITLE
unit test failed

### ISSUE THREAD

**Issue by sumpan** [salesforce/Argus#666]
![image](https://user-images.githubusercontent.com/6269809/30900109-3993336a-a395-11e7-9cfd-c9568559238e.png)
when i try to run unit test,error occur see picture above.
I put persistence.xml under test resources dir
![image](https://user-images.githubusercontent.com/6269809/30900165-7a51a7b0-a395-11e7-8708-b1c095906f37.png)
and argus.properties has config items for jpa
![image](https://user-images.githubusercontent.com/6269809/30900186-96ad835c-a395-11e7-8919-43a013a4a6ac.png)
 bug every time ，I would see that error, can you help me to solve it?

java.lang.IllegalArgumentException: Unknown Entity bean class: class com.salesforce.dva.argus.entity.PrincipalUser, please verify that this class has been marked with the @Entity annotation.
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:718)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:599)

**Comment by sumpan** [comment]
![image](https://user-images.githubusercontent.com/6269809/30900275-f8ba589a-a395-11e7-8179-23536f156378.png)
jpa properties in argus.properties will overwrite properties in persistence.xml ？
so I hava no properties settings in persistence.xml

**Comment by rajsarkapally** [comment]
Argus no longer requires persistence.properties file as we added the persistence details to argus-build.properties file.
Here is the property
build.property.persistence.unit=<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>\n    <exclude-unlisted-classes>false</exclude-unlisted-classes>\n    <properties>\n      <property name="javax.persistence.schema-generation.database.action" value="drop-and-create-tables"/>\n      <property name="javax.persistence.jdbc.driver" value="org.apache.derby.jdbc.EmbeddedDriver"/>\n      <property name="javax.persistence.jdbc.url" value="jdbc:derby:memory:argus;create=true"/>\n      <property name="javax.persistence.jdbc.user" value="root"/>\n      <property name="javax.persistence.jdbc.password" value="root"/>\n      <property name="eclipselink.ddl-generation" value="drop-and-create-tables"/>\n      <property name="eclipselink.logging.level" value="SEVERE"/>\n      <property name="eclipselink.logging.parameters" value="true"/>\n      <property name="eclipselink.target-database" value="DERBY"/>\n      <property name="eclipselink.canonicalmodel.subpackage" value="unit"/>\n    </properties>
