### ISSUE TITLE
Stackoverflow error when using CachedTsdbService

### ISSUE THREAD

**Issue by sgarg7** [salesforce/Argus#688]
I'm seeing the following error in a loop after changing the 
`service.binding.tsdb` property to `com.salesforce.dva.argus.service.tsdb.CachedTSDBService`  

`	[ ARGUS | *NULLSESSION* | *NULLUSER* | *NULLTXID* | 2017-11-10 17:02:00.801 | AlertScheduler_Worker-2 | ERROR ] Job (DEFAULT.6da64b5bd2ee-77df724a-d36c-4aa7-81d9-c5908dea58a1 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.StackOverflowError: null
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy20.putMetrics(Unknown Source)
	at com.salesforce.dva.argus.service.tsdb.CachedTSDBService.putMetrics(CachedTSDBService.java:571)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy20.putMetrics(Unknown Source)
	at com.salesforce.dva.argus.service.tsdb.CachedTSDBService.putMetrics(CachedTSDBService.java:571)`

My guess is that since the CachedTSDBService [requires an instance of type TsdbService](https://github.com/salesforce/Argus/blob/develop/ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/CachedTSDBService.java#L103) to query OpenTsdb (which is done by the SingletonTSDBService/DefaultTSDBService), but CachedTSDBService gets passed in due to the service.binding.tsdb property, which leads to the error. 

Have you seen this issue happening? Is there a different property setting I'm missing that can help prevent it?

**Comment by bsura** [comment]
You should use SingletonTSDBService for tsdb service binding. 

`service.binding.tsdb=com.salesforce.dva.argus.service.tsdb.SingletonTSDBService`

**Comment by sgarg7** [comment]
I want to use OpenTSDB with Redis for caching. I believe CachedTSDBService
is the right class to use for that?

**Comment by bsura** [comment]
The way we have implemented this is that internally we always use CachedTSDBService. CachedTSDBService is injected with 2 things: 
1. The CacheService implementation to use (If you want to disable caching, then use NoOperationCacheService)
2. The TSDBService implementation to use when underneath (This is what you configure using "service.binding.tsdb")

Makes sense?

**Comment by sgarg7** [comment]
Thanks for the reply. That makes sense. It basically worked for me (not getting StackOverflow error, but unable to connect to the redis cluster). I will try to figure that out now. Closing.
