### ISSUE TITLE
Error in sending emails

### ISSUE THREAD

**Issue by amitkumar912** [salesforce/Argus#693]
Hi - 
I have my smtp properties set to send email as such: 
~~~
system.property.mail.enabled=true
service.binding.mail=com.salesforce.dva.argus.service.mail.DefaultMailService
service.property.mail.smtp.host=mail.company.com
service.property.mail.smtp.auth=false
service.property.mail.smtp.starttls.enable=false
service.property.mail.smtp.starttls.required=false
service.property.mail.email.transport.protocol=smtp
service.property.mail.smtp.port=25
service.property.smtp.port=25
~~~

However in my logs it keeps throwing an error and is trying to use a different port than what i specified.
~~~
[ ARGUS | *NULLSESSION* | *NULLUSER* | *NULLTXID* | 2017-11-20 15:47:15.504 | alertclient-1 | ERROR ] MailService: Failed to send an email notification.
javax.mail.MessagingException: Could not connect to SMTP host: mail.factset.com, port: 465
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at com.salesforce.dva.argus.service.mail.DefaultMailService.sendMessage(DefaultMailService.java:133)
	at com.salesforce.dva.argus.service.alert.notifier.EmailNotifier.sendAdditionalNotification(EmailNotifier.java:103)
	at com.salesforce.dva.argus.service.alert.notifier.DefaultNotifier.sendNotification(DefaultNotifier.java:99)
	at com.salesforce.dva.argus.service.alert.DefaultAlertService._sendNotification(DefaultAlertService.java:485)
	at com.salesforce.dva.argus.service.alert.DefaultAlertService._processNotification(DefaultAlertService.java:413)
	at com.salesforce.dva.argus.service.alert.DefaultAlertService.executeScheduledAlerts(DefaultAlertService.java:361)
	at com.salesforce.dva.argus.service.alert.DefaultAlertService$$EnhancerByGuice$$6e413c20.CGLIB$executeScheduledAlerts$10(<generated>)
	at com.salesforce.dva.argus.service.alert.DefaultAlertService$$EnhancerByGuice$$6e413c20$$FastClassByGuice$$c71348e8.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
........................
~~~

465 is one of the default SMTP ports, however its one of a few. 25 is also another one. Any ideas on what could be wrong here?

Thanks.

**Comment by amitkumar912** [comment]
Turns out I had the wrong protocol value set. When I added this line, it fixed itself:
~~~
service.property.email.transport.protocol=smtp
~~~
